### ISSUE TITLE
Installation fails at vagrant up

### ISSUE THREAD

**Issue by ywarnier** [CampFireManager/cfm3#6]
Hi, I just cloned cfm3 on Ubuntu 13.04 and when following the install guide (installing vagrant through apt-get install vagrant, which downloaded package vagrant 1.0.3-1ubuntu3), I get the following long error:

/var/www/cfm3/Vagrantfile:1:in `<top (required)>': undefined method`configure' for Vagrant:Module (NoMethodError)
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:115:in `load'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:115:in`block in procs_for_source'
    from /usr/lib/ruby/vendor_ruby/vagrant/config.rb:41:in `block in capture_configures'
    from <internal:prelude>:10:in`synchronize'
    from /usr/lib/ruby/vendor_ruby/vagrant/config.rb:36:in `capture_configures'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:114:in`procs_for_source'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:51:in `block in set'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:45:in`each'
    from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:45:in `set'
    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:377:in`block in load_config!'
    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:392:in `call'
    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:392:in`load_config!'
    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:327:in `load!'
    from /usr/bin/vagrant:40:in`<main>'

**Comment by BinaryKitten** [comment]
Hi @ywarnier 

Vagrant 1.0.3 is massively out of date. Would recommend upgrading using the deb on vagrantup.com

**Comment by BinaryKitten** [comment]
I'll be replacing the vagrant install/config later today to work better.
